"""models changed фпagain

Revision ID: 78008b749bca
Revises: 34130c46393c
Create Date: 2025-04-28 21:41:46.117078

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78008b749bca'
down_revision: Union[str, None] = '34130c46393c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('description', sa.JSON(), nullable=False))
    op.add_column('campaign', sa.Column('view_price', sa.Integer(), nullable=False))
    op.add_column('integration', sa.Column('links', sa.JSON(), nullable=True))
    op.add_column('integration', sa.Column('views_count', sa.Integer(), nullable=False))
    op.drop_column('integration', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('integration', 'views_count')
    op.drop_column('integration', 'links')
    op.drop_column('campaign', 'view_price')
    op.drop_column('campaign', 'description')
    # ### end Alembic commands ###
