"""links and publications changed

Revision ID: cf3d857f026f
Revises: 78008b749bca
Create Date: 2025-04-29 10:38:15.781458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf3d857f026f'
down_revision: Union[str, None] = '78008b749bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogger', sa.Column('profile_links', sa.JSON(), nullable=True))
    op.add_column('integration', sa.Column('publication_links', sa.JSON(), nullable=True))
    op.drop_column('integration', 'links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('integration', 'publication_links')
    op.drop_column('blogger', 'profile_links')
    # ### end Alembic commands ###
