"""payment models added

Revision ID: eeeff7cb3640
Revises: cf3d857f026f
Create Date: 2025-04-29 11:13:29.286247

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eeeff7cb3640'
down_revision: Union[str, None] = 'cf3d857f026f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogger_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blogger_id', sa.Integer(), nullable=False),
    sa.Column('money_amount', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blogger_id'], ['blogger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('money_amount', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogger', sa.Column('approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogger', 'approved')
    op.drop_table('company_payment')
    op.drop_table('blogger_payment')
    # ### end Alembic commands ###
